# watchlist.py — Time-sensitive topics the curator + note writer should flag
#
# Two layers feed the watchlist:
#   1. MANUAL — vault/wiki/watchlist.md, edited by Rafael directly. Read on
#      every pipeline run. Highest priority. Add a topic by appending one line
#      under "## Active". Move to "## Resolved" when stale.
#
#   2. AUTO   — output/auto_suggested_topics.md, refreshed every learn cycle.
#      Claude mines recent News Writer conversations + wiki pages for topics
#      Rafael is actively discussing that the curator doesn't know about yet.
#      Lower priority — advisory, until promoted to manual.
#
# Both get injected into CATEGORISE_SYSTEM and NOTE_SYSTEM at call time so the
# curator FLAGS matching headlines instead of treating them as routine color.

import os
import re
import sys
from datetime import datetime
from typing import List, Optional

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# ── Paths ─────────────────────────────────────────────────────────────────────
_HERE        = os.path.dirname(os.path.abspath(__file__))
_VAULT_ROOT  = r"C:\Users\Rafael\OneDrive\Documentos\Obsidian Vault"

WATCHLIST_PATH         = os.path.join(_VAULT_ROOT, "wiki", "watchlist.md")
AUTO_SUGGESTED_PATH    = os.path.join(_HERE, "output", "auto_suggested_topics.md")

_MAX_WATCHLIST_CHARS   = 4000   # safety cap so the prompt doesn't bloat


# ── Loaders ───────────────────────────────────────────────────────────────────
def load_manual_watchlist() -> str:
    """
    Load Rafael's manual watchlist from vault/wiki/watchlist.md.
    Only the "## Active" section is returned — "## Resolved" is ignored so
    decayed topics don't keep firing.
    """
    if not os.path.exists(WATCHLIST_PATH):
        return ""
    try:
        with open(WATCHLIST_PATH, encoding="utf-8", errors="replace") as f:
            content = f.read()
    except OSError:
        return ""

    # Extract only the "## Active" section (stop at next ## heading or EOF)
    m = re.search(
        r"##\s*Active\s*\n([\s\S]*?)(?:\n##\s|\Z)",
        content, re.IGNORECASE,
    )
    active = (m.group(1) if m else content).strip()
    return active[:_MAX_WATCHLIST_CHARS]


def load_auto_suggestions() -> str:
    """Load auto-suggested topics last extracted by the learn cycle."""
    if not os.path.exists(AUTO_SUGGESTED_PATH):
        return ""
    try:
        with open(AUTO_SUGGESTED_PATH, encoding="utf-8", errors="replace") as f:
            return f.read().strip()[:_MAX_WATCHLIST_CHARS]
    except OSError:
        return ""


# ── Build the prompt-injection block ──────────────────────────────────────────
def build_watchlist_text() -> str:
    """
    Build the watchlist injection block. Combines manual (highest priority)
    and auto-suggested (advisory). Returns "" when both are empty so callers
    can no-op cleanly.
    """
    manual = load_manual_watchlist()
    auto   = load_auto_suggestions()

    if not manual and not auto:
        return ""

    parts: List[str] = [
        "### CURRENT WATCH TOPICS (refreshed every run)",
        "",
        "If a headline matches any topic below — even loosely — FLAG IT as material.",
        "These are time-sensitive themes Rafael is actively tracking; do NOT treat",
        "as routine sector color. Promote to a full note when the headline carries a",
        "concrete development (decision, ruling, deal, datapoint), not just commentary.",
        "",
    ]

    if manual:
        parts.append("--- Manual watchlist (user-curated, HIGHEST PRIORITY) ---")
        parts.append(manual)
        parts.append("")

    if auto:
        parts.append("--- Auto-suggested topics (from recent News Writer activity) ---")
        parts.append(auto)
        parts.append("")

    return "\n".join(parts).rstrip()


# ── Save auto-suggested topics (called from learn.py) ─────────────────────────
def save_auto_suggestions(text: str) -> Optional[str]:
    """Write auto-suggested topics to disk so they're available on every run."""
    if not text or not text.strip():
        return None
    try:
        os.makedirs(os.path.dirname(AUTO_SUGGESTED_PATH), exist_ok=True)
        header = (
            f"<!-- Auto-generated by learn.py on "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M')} -->\n"
            "<!-- Topics extracted from recent News Writer vault sessions. -->\n"
            "<!-- Promote any of these to vault/wiki/watchlist.md to lock them in. -->\n\n"
        )
        with open(AUTO_SUGGESTED_PATH, "w", encoding="utf-8") as f:
            f.write(header + text.strip() + "\n")
        return AUTO_SUGGESTED_PATH
    except OSError as e:
        print(f"  [WARN] Could not save auto-suggested topics: {e}")
        return None


# ── Bootstrap helper: create a starter watchlist.md if one doesn't exist ──────
_STARTER_WATCHLIST = """# Current Watch Topics

Time-sensitive topics the news scraper should flag whenever they appear in a
headline. Edit this file directly — changes take effect on the next pipeline run.

**How to use:**
- Drop a one-liner under `## Active` with: TOPIC — why it matters, which covered
  tickers it affects, what to watch for.
- When a topic resolves (deal closed, ruling passed, story stale), move it to
  `## Resolved` — it stops firing but stays as historical context.
- Keep entries SHORT. The whole `## Active` block gets injected into Claude's
  prompt on every run, so trim aggressively.

---

## Active

- **FISTEL** — Brazilian telecom regulatory fee. Material for VIVT3 / TIMS3 /
  Brisanet / Desktop cost structure. Flag any change in calculation, exemptions,
  congressional bill, court ruling, Anatel proposal, or fee waiver discussion.

## Resolved
"""


def bootstrap_watchlist_file() -> bool:
    """
    Create a starter vault/wiki/watchlist.md if it doesn't exist yet.
    Returns True if the file was newly created, False if it already existed.
    """
    if os.path.exists(WATCHLIST_PATH):
        return False
    try:
        os.makedirs(os.path.dirname(WATCHLIST_PATH), exist_ok=True)
        with open(WATCHLIST_PATH, "w", encoding="utf-8") as f:
            f.write(_STARTER_WATCHLIST)
        return True
    except OSError as e:
        print(f"  [WARN] Could not bootstrap watchlist.md: {e}")
        return False


# ── CLI ───────────────────────────────────────────────────────────────────────
def main() -> None:
    """python watchlist.py — show what's currently being watched."""
    if "--bootstrap" in sys.argv:
        created = bootstrap_watchlist_file()
        if created:
            print(f"  Created starter file: {WATCHLIST_PATH}")
        else:
            print(f"  File already exists: {WATCHLIST_PATH}")
        return

    text = build_watchlist_text()
    if not text:
        print("(no watchlist topics yet)")
        print()
        print(f"  Manual watchlist path: {WATCHLIST_PATH}")
        print(f"  Auto-suggested path:   {AUTO_SUGGESTED_PATH}")
        print()
        print("  Run 'python watchlist.py --bootstrap' to create a starter "
              "watchlist.md in the vault.")
    else:
        print(text)


if __name__ == "__main__":
    main()
